name: Run Simple Code

on:
  push:
    branches:
      - main

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Simple Code
        run: |
          echo "Hello, World!"
      
